import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
import { JSDOM } from 'jsdom';
const html = await readFile('dist/index.html', 'utf8');
const script = html.match(/src="([^"]+\.js)"/)[1];
const source = await readFile(`dist${script}`, 'utf8');
const dom = new JSDOM('<div id="root"></div>', {url:'http://localhost:5173',runScripts:'outside-only',pretendToBeVisual:true});
const {window:w} = dom;
const doc=w.document;
let opened;
w.open=(...args)=>{opened=args};
w.HTMLDialogElement.prototype.showModal=function(){this.open=true};
w.HTMLDialogElement.prototype.close=function(){this.open=false};
w.eval(source);
const tick=()=>new Promise(r=>setTimeout(r,40));
await tick();
const click=async(el)=>{assert.ok(el);el.click();await tick()};
const button=(text)=>[...doc.querySelectorAll('button')].find(el=>el.textContent.includes(text));
assert.match(doc.querySelector('h1').textContent,/Make Maths click/);
await click(button('Practise it'));
assert.match(doc.querySelector('[role="tabpanel"]').textContent,/Turn “I think”/);
await click(button('How much do classes cost?'));
assert.equal(button('How much do classes cost?').getAttribute('aria-expanded'),'true');
await click(button('How much do classes cost?'));
assert.equal(button('How much do classes cost?').getAttribute('aria-expanded'),'false');
await click(doc.querySelector('.menu-button'));
assert.equal(doc.querySelector('.menu-button').getAttribute('aria-expanded'),'true');
await click(doc.querySelector('nav a'));
assert.equal(doc.querySelector('.menu-button').getAttribute('aria-expanded'),'false');
await click(button('Book my free trial'));
assert.equal(doc.querySelector('dialog').open,true);
assert.equal(doc.querySelector('form').checkValidity(),false);
for(const [name,value] of Object.entries({name:'Alex Test',grade:'Year 7',city:'London, UK',subject:'Fractions & algebra'})) doc.querySelector(`[name="${name}"]`).value=value;
assert.equal(doc.querySelector('form').checkValidity(),true);
doc.querySelector('form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
assert.match(opened[0],/^https:\/\/wa.me\/919373438129\?/);
assert.match(new URL(opened[0]).searchParams.get('text'),/Fractions & algebra/);
assert.match(new URL(opened[0]).searchParams.get('text'),/London, UK/);
await click(doc.querySelector('.dialog-close'));
assert.equal(doc.querySelector('dialog').open,false);
assert.equal(doc.body.style.overflow,'');
for(const a of doc.querySelectorAll('a[href^="#"]'))assert.ok(doc.querySelector(a.getAttribute('href')));
await click(button('Try a free Science class'));
assert.equal(doc.querySelector('[name="subject"]').value,'Science');
doc.querySelector('[name="board"]').value='National board';
doc.querySelector('form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
assert.match(new URL(opened[0]).searchParams.get('text'),/Board \/ curriculum: National board/);
await click(doc.querySelector('.dialog-close'));
await click(button('$5'));
assert.match(doc.querySelector('.challenge-feedback').textContent,/Have another go/);
await click(button('$15'));
assert.match(doc.querySelector('.challenge-feedback').textContent,/That.s it/);
await click([...doc.querySelectorAll('.challenge-switch button')].find(el=>el.textContent==='Science'));
assert.match(doc.querySelector('.challenge-feedback').textContent,/Pick an answer/);
await click(button('Light'));
assert.match(doc.querySelector('.challenge-feedback').textContent,/phototropism/);
await click(doc.querySelector('.reset-challenge'));
assert.match(doc.querySelector('.challenge-feedback').textContent,/Pick an answer/);
await click(button('Explore more in a free class'));
assert.equal(doc.querySelector('[name="subject"]').value,'Science');
await click(doc.querySelector('.dialog-close'));
console.log('PASS: subject enquiries, curriculum handoff, challenge hints, correct answers, subject switching, reset; page render, learning tabs, FAQ toggle, mobile navigation, trial validation, WhatsApp handoff, dialog close, and section links.');

await click(button('Discover my starting point'));
assert.equal(button('Next question').disabled,true);
const choose = async (index) => click(doc.querySelectorAll('.explorer-options button')[index]);
await choose(2);
await click(button('Next question'));
await choose(1);
await click([...doc.querySelectorAll('.explorer-actions button')].find(el=>el.textContent.includes('Back')));
assert.equal(doc.querySelectorAll('.explorer-options button')[2].getAttribute('aria-pressed'),'true');
await click(button('Next question'));
assert.equal(doc.querySelectorAll('.explorer-options button')[1].getAttribute('aria-pressed'),'true');
await click(button('Next question'));
await choose(0);
await click(button('Next question'));
await choose(1);
await click(button('Next question'));
assert.ok(doc.querySelector('.number-pattern'));
await choose(1);
await click(button('Next question'));
assert.ok(doc.querySelector('.state-diagram'));
await choose(0);
await click(button('See my snapshot'));
assert.match(doc.querySelector('.result-grid').textContent,/Maths & Science/);
assert.equal(doc.querySelector('.score-circle').textContent,'2/ 2');
assert.match(doc.querySelector('.answer-review').textContent,/Each number doubles/);
assert.match(doc.querySelector('.answer-review').textContent,/Melting changes/);
await click(button('Use my snapshot for a free trial'));
assert.match(doc.querySelector('[name="subject"]').value,/Quick check: 2\/2/);
assert.match(doc.querySelector('[name="subject"]').value,/Ask someone for a hint/);
assert.ok(doc.querySelector('[name="subject"]').value.length<=600);
doc.querySelector('form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
assert.match(new URL(opened[0]).searchParams.get('text'),/My learning snapshot/);
await click(doc.querySelector('.dialog-close'));
await click(button('Start again'));
await click(button('Discover my starting point'));
assert.equal(button('Next question').disabled,true);
for(let i=0;i<6;i++){
  await choose(i===5?1:0);
  await click(button(i===5?'See my snapshot':'Next question'));
}
assert.equal(doc.querySelector('.score-circle').textContent,'0/ 2');
assert.match(doc.querySelector('.answer-review').textContent,/Something to explore together/);
assert.equal(w.localStorage.length,0);
console.log('PASS: discovery test requires answers, supports back navigation, preserves selections, scores 2/2 and 0/2 correctly, explains answers, resets, and shares the snapshot only through the trial flow.');
w.close();
