import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowUpRight, ArrowRight, BookOpen, Check, ChevronDown, Globe2, Menu, X, MessageCircle, Sparkles, Clock3, Heart, Lightbulb, Pencil, Video, Mic, Monitor, GraduationCap, MoveUpRight } from 'lucide-react';
import './styles.css';
import Subjects from './Subjects';
import LearningExplorer from './LearningExplorer';
import LearningMap from './LearningMap';
import './readability.css';

const phone = '919373438129';
const whatsapp = (message = 'Hi! I would like to know more about one-to-one classes at Kulkarni Academy.') => `https://wa.me/${phone}?text=${encodeURIComponent(message)}`;
const faqs = [
  ['How does the free trial work?', 'Send a trial request with a little about the student and what they need help with. We’ll chat on WhatsApp to confirm the subject, find a suitable time, and arrange a free introductory class. No payment is needed to request a trial.'],
  ['Which subjects and year groups do you teach?', 'We teach Maths and Science across all national and international boards. Share the student’s year group, board, and current topics so we can plan a trial around their syllabus and learning needs.'],
  ['Can you work around our time zone?', 'Yes. We welcome students in Singapore, the UK, Texas, and beyond. Share your city and preferred availability, and we’ll agree on a class time together. All times are confirmed before the class.'],
  ['How much do classes cost?', 'Paid classes range from $15 to $30 USD per class. The exact fee depends on the student’s level and learning requirements and will be agreed with you before paid classes begin.'],
  ['What do we need for an online class?', 'A reliable internet connection, a laptop or tablet with a microphone, and a notebook are a great start. We’ll share the meeting link and any specific materials before your first class.'],
];

function Brand() {return <a href="#home" className="brand" aria-label="Kulkarni Academy home"><span className="academy-logo"><img src="/kulkarni-academy-logo.png" alt="" width="1536" height="2752" decoding="async" /></span><span>Kulkarni<span className="brand-sub">ACADEMY</span></span></a>}
function App(){
 const [menu,setMenu]=useState(false), [modal,setModal]=useState(false), [faq,setFaq]=useState(0), [focus,setFocus]=useState(0);
 const dialog=useRef(null); const previousFocus=useRef(null);
 const openTrial=(subject='')=>{previousFocus.current=document.activeElement;if(typeof subject==='string' && subject){dialog.current.querySelector('[name=subject]').value=subject;}setMenu(false);setModal(true)};
 useEffect(()=>{if(modal){dialog.current.showModal();document.body.style.overflow='hidden'}else{dialog.current?.close();document.body.style.overflow='';previousFocus.current?.focus()}return()=>{document.body.style.overflow=''}},[modal]);
 const submitTrial=(event)=>{event.preventDefault(); const data=new FormData(event.currentTarget);const message=`Hi Kulkarni Academy! I'd like to arrange a free trial.\nName: ${data.get('name').trim()}\nStudent’s year / grade: ${data.get('grade').trim()}\nBoard / curriculum: ${data.get('board').trim() || 'To discuss'}\nSubject / learning goal: ${data.get('subject').trim()}\nCity / time zone: ${data.get('city').trim()}`;window.open(whatsapp(message),'_blank','noopener,noreferrer');};
 const focusContent=[{label:'Understand it',title:'Make the tricky things click.',text:'Room to ask “why?”, revisit a concept, and learn at a pace that feels right. Understanding comes before moving on.',icon:<Lightbulb/>},{label:'Practise it',title:'Turn “I think” into “I know.”',text:'Work through questions together, talk through each step, and build confidence by putting understanding into practice.',icon:<Pencil/>},{label:'Own it',title:'A little more independent, every day.',text:'Build the habits to approach new questions, explain your thinking, and feel more comfortable learning on your own.',icon:<GraduationCap/>}];
 return <>
 <header><div className="nav-wrap"><Brand/><nav aria-label="Main navigation" className={menu?'nav open':'nav'}>{[['Subjects','subjects'],['Student test','learning-check'],['How it works','how-it-works'],['Pricing','pricing'],['FAQs','faqs']].map(([label,id])=><a href={`#${id}`} key={id} onClick={()=>setMenu(false)}>{label}</a>)}</nav><button className="button nav-cta" onClick={openTrial}>Book a free trial <ArrowUpRight size={17}/></button><button className="menu-button" aria-label={menu?'Close menu':'Open menu'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>
 <main>
 <section className="hero section-wrap" id="home"><div className="hero-copy"><span className="eyebrow"><span className="status-dot"/> MATHS & SCIENCE / ONE-TO-ONE ONLINE TUITION</span><h1>Make Maths click.<br/>Let Science<br/><span className="word-highlight">spark curiosity.<svg viewBox="0 0 420 18" preserveAspectRatio="none" aria-hidden="true"><path d="M3 12Q210-8 415 9M70 17Q260 1 380 14"/></svg></span></h1><p>Maths & Science for all national and international boards.<br className="desktop-break"/> One student. One tutor. Every question welcome.</p><p className="hero-detail">Personal online tuition that turns “I can’t” into “I’ve got this.”<br className="desktop-break"/> From wherever in the world you call home.</p><div className="hero-actions"><button className="button primary" onClick={openTrial}>Book your free trial class <ArrowUpRight size={19}/></button><a className="text-link" href={whatsapp()} target="_blank" rel="noreferrer"><MessageCircle size={18}/> Let’s chat</a></div><a className="explore-subjects" href="#learning-check">Try the student discovery test <ArrowRight size={16}/></a><div className="reassurance"><span><Check/> No commitment</span><span><Check/> Just you & your tutor</span><span><Check/> 100% online</span></div></div>
 <div className="hero-art" aria-label="Illustration of a personal online learning session"><div className="art-dot-pattern"/><span className="floating-tag personal"><Sparkles size={16}/> A classroom of one.</span><div className="session-card"><div className="session-top"><span><span className="live-dot"/> MATHS + SCIENCE</span><span>1 : 1 SESSION</span></div><div className="lesson-area"><div className="lesson-title"><span className="lesson-pill">THE BEAUTY OF A LITTLE “AHA!”</span><span className="hand-star">✳</span></div><div className="equation">Think. Explore.<br/><span>Understand the why.</span></div><div className="graph"><svg viewBox="0 0 370 165" role="img" aria-label="A learning journey growing with practice"><defs><pattern id="grid" width="30" height="30" patternUnits="userSpaceOnUse"><path d="M 30 0 L 0 0 0 30" fill="none" stroke="#dedbd0" strokeWidth="1"/></pattern></defs><rect width="370" height="165" fill="url(#grid)"/><path d="M20 138H351M31 151V10" fill="none" stroke="#8b8f78" strokeWidth="1.5"/><path d="M43 125C95 122 99 94 139 100S190 78 218 71S270 58 320 18" fill="none" stroke="#6a59ae" strokeWidth="4" strokeLinecap="round"/><path d="m303 18 19-2-5 18" fill="none" stroke="#6a59ae" strokeWidth="4" strokeLinecap="round"/><circle cx="139" cy="100" r="6" fill="#b3bf91" stroke="#fff" strokeWidth="3"/><circle cx="218" cy="71" r="6" fill="#b3bf91" stroke="#fff" strokeWidth="3"/></svg><span className="graph-note">your confidence ↗</span></div><div className="lesson-bottom"><span><Pencil size={13}/> A little practice, a lot of possibility.</span><span className="drawn-smile">☺</span></div></div><div className="call-bar"><span><span className="mini-avatar">K</span> Kulkarni Academy</span><div><span><Mic size={14}/></span><span><Video size={14}/></span><span><Monitor size={14}/></span></div></div></div><div className="floating-tag aha"><span className="aha-icon"><Lightbulb size={23}/></span><div>“Oh, now I get it!”<small>Our favourite kind of moment.</small></div></div><div className="scribble">a little more confident,<br/>one class at a time <span>↗</span></div><span className="art-spark">✧</span></div>
 </section>
 <section className="world-strip"><div className="section-wrap world-inner"><div><Globe2 size={22}/><span>Different time zones.<br/><strong>The same personal attention.</strong></span></div><div className="locations"><span><span className="location-dot mint"/> Singapore</span><span><span className="location-dot peach"/> Texas, USA</span><span><span className="location-dot purple"/> London, UK</span><span className="anywhere">& wherever you are <ArrowUpRight size={15}/></span></div></div></section>
 <Subjects onTrial={openTrial}/><LearningExplorer onTrial={openTrial}/><section className="approach section-wrap section-space" id="approach"><div className="section-heading"><div><span className="eyebrow">LESS PRESSURE. MORE POSSIBILITY.</span><h2>Learning feels different<br/>when it’s <span className="serif">made for you.</span></h2></div><p>A simple path from your first question<br/>to your next breakthrough.</p></div><LearningMap/>
 <div className="learning-panel"><div className="learning-intro"><span className="eyebrow">THE LITTLE STEPS ADD UP</span><h3>Not just the answer.<br/>The confidence to find it.</h3><div className="learning-tabs" role="tablist" aria-label="Learning approach">{focusContent.map((item,i)=><button role="tab" id={`tab-${i}`} aria-selected={focus===i} aria-controls="learning-content" key={item.label} onClick={()=>setFocus(i)} className={focus===i?'selected':''}>{item.label}<ArrowUpRight size={15}/></button>)}</div></div><div className="learning-content" id="learning-content" role="tabpanel" aria-labelledby={`tab-${focus}`} key={focus}><span className="learning-icon">{focusContent[focus].icon}</span><h3>{focusContent[focus].title}</h3><p>{focusContent[focus].text}</p></div></div></section>
 <section className="steps-section" id="how-it-works"><div className="section-wrap section-space"><div className="center-heading"><span className="eyebrow">A SIMPLE START</span><h2>Your next chapter starts here.</h2><p>No complicated sign-ups. Just a conversation.</p></div><div className="steps">{[['01','Say hello','Share your subject + goal.'],['02','Meet in a free trial','Meet your tutor. Try a lesson.'],['03','Find your rhythm','Choose a time. Build confidence.']].map(([n,title,text])=><article key={n}><span className="step-number">{n}<ArrowRight size={20}/></span><h3>{title}</h3><p>{text}</p></article>)}</div><button className="text-link purple-link" onClick={openTrial}>Take the first little step <ArrowUpRight size={19}/></button></div></section>
 <section className="pricing section-wrap section-space" id="pricing"><div className="pricing-copy"><span className="eyebrow">PERSONAL LEARNING. CLEAR PRICING.</span><h2>A little investment.<br/><span className="serif">A brighter tomorrow.</span></h2><p>Quality one-to-one attention, with a fee agreed upfront.<br/>Start with a free trial and see if we’re a good fit.</p><div className="pricing-note"><span className="icon-box green"><MessageCircle/></span><div><strong>Not sure where to start?</strong><p>That’s what the first conversation is for.</p><a href={whatsapp()} target="_blank" rel="noreferrer">Talk to us on WhatsApp <ArrowUpRight size={15}/></a></div></div></div><div className="price-card"><span className="price-badge"><Sparkles size={13}/> YOUR FIRST CLASS IS ON US</span><div className="price-top"><span className="eyebrow">ONE-TO-ONE ONLINE TUITION</span><div className="price">$15<span>–</span>$30 <small>USD / class</small></div><p>Individual attention. Real understanding.</p></div><ul>{['One student, one dedicated tutor','Lessons shaped around your learning needs','Class timings agreed around your time zone','A free trial to find your fit'].map(item=><li key={item}><span><Check size={14}/></span>{item}</li>)}</ul><button className="button primary" onClick={openTrial}>Let’s start with a free class <ArrowUpRight size={18}/></button><p className="fine-print">Final fee depends on level and learning requirements.<br/>We’ll confirm the details before paid classes begin.</p></div></section>
 <section className="faq-section section-wrap section-space" id="faqs"><div><span className="eyebrow">A LITTLE CLARITY</span><h2>Good questions.<br/><span className="serif">Honest answers.</span></h2><p>Something else on your mind?</p><a className="text-link purple-link" href={whatsapp()} target="_blank" rel="noreferrer">We’re a message away <ArrowUpRight size={17}/></a></div><div className="faq-list">{faqs.map(([q,a],i)=><article className={faq===i?'faq-item expanded':'faq-item'} key={q}><h3><button aria-expanded={faq===i} aria-controls={`faq-${i}`} onClick={()=>setFaq(faq===i?null:i)}>{q}<ChevronDown size={18}/></button></h3><div id={`faq-${i}`} hidden={faq!==i}><p>{a}</p></div></article>)}</div></section>
 <section className="final-cta section-wrap"><span className="cta-star" aria-hidden="true">✳</span><div><span className="eyebrow">EVERY GREAT JOURNEY STARTS WITH A HELLO.</span><h2>Let’s see what’s possible. <span className="serif">Together.</span></h2><p>Your first class is free. Your next chapter is waiting.</p></div><button className="button dark" onClick={openTrial}>Book my free trial <ArrowUpRight size={19}/></button></section>
 </main><aside className="quick-contact" aria-label="Quick contact"><a href={whatsapp()} target="_blank" rel="noreferrer" aria-label="Chat with Kulkarni Academy on WhatsApp"><MessageCircle size={20}/><span>Let’s talk</span></a><button onClick={openTrial}>Free trial class <ArrowUpRight size={17}/></button></aside><footer className="section-wrap"><div className="footer-top"><Brand/><p>Personal attention.<br/>Possibilities without borders.</p><a href="tel:+919373438129">+91 93734 38129 <ArrowUpRight size={16}/></a><a href={whatsapp()} target="_blank" rel="noreferrer"><MessageCircle size={18}/> Say hello on WhatsApp</a></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Kulkarni Academy. Made for curious minds.</span><span>Based in India. Connected to your world. <Globe2 size={14}/></span></div></footer>
 <dialog ref={dialog} className="trial-dialog" onCancel={()=>setModal(false)} onClick={e=>{if(e.target===dialog.current)setModal(false)}}><button className="dialog-close" aria-label="Close trial enquiry" onClick={()=>setModal(false)}><X/></button><span className="icon-box lilac"><Sparkles/></span><span className="eyebrow">A LITTLE HELLO. A GREAT START.</span><h2>Find your spark.</h2><p>Tell us a little about yourself. We’ll open WhatsApp with your enquiry ready for you to send.</p><form onSubmit={submitTrial}><label>Your name<input name="name" autoComplete="name" placeholder="Parent or student’s name" required maxLength={80}/></label><div className="form-row"><label>Year / grade<input name="grade" placeholder="e.g. Year 7" required maxLength={60}/></label><label>City / time zone<input name="city" placeholder="e.g. London, UK" required maxLength={100}/></label></div><label>School board / curriculum <span className="optional-label">(optional)</span><input name="board" placeholder="Your national or international board" maxLength={100}/></label><label>What would you like help with?<textarea name="subject" placeholder="Share the subject, curriculum, or a learning goal…" required maxLength={600} rows={3}/></label><button className="button primary" type="submit"><MessageCircle size={19}/> Continue on WhatsApp <ArrowUpRight size={18}/></button><small>Your request isn’t a confirmed booking. We’ll agree on a time in our chat. These details are passed to WhatsApp only when you continue.</small></form><a className="direct-contact" href="tel:+919373438129">Prefer a call? +91 93734 38129</a></dialog>
 </>;
}
createRoot(document.getElementById('root')).render(<App/>);
